source 'https://rubygems.org'


gem 'rails', '4.2.3'
gem 'pg'
gem 'jbuilder', '~> 2.0'
gem "paperclip", :git => "git://github.com/thoughtbot/paperclip.git"
gem 'aws-sdk'

# gem 'sdoc', '~> 0.4.0', group: :doc


group :development, :test do

  gem 'pry'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'sass-rails', '~> 5.0'
  gem 'uglifier', '>= 1.3.0'
  gem 'browserify-rails'
  gem 'dotenv-rails'
end
